import { useRef, useEffect, useState } from 'react';
import { Icon } from '../icons';
import { ARTIFACT_CONFIG, ARTIFACT_DISPLAY_NAME } from '../../data/mockSession';
import { useSessionStore } from '../../store/useSessionStore';
import type { Artifact } from '../../types';

const FILTER_TYPES = ['All', 'Chart', 'Table', 'KeyFinding', 'CleaningLedger', 'Narrative'];

function ArtifactPayloadContent({ art }: { art: Artifact }) {
  // If payload has structured data, show it; otherwise show a generic preview
  const isEmpty = Object.keys(art.payload).length === 0;

  if (isEmpty) {
    return (
      <div style={{ marginTop: 8, fontSize: 12, color: 'var(--text-muted)', fontStyle: 'italic' }}>
        No preview available — content generated by agent.
      </div>
    );
  }

  // Render known payload shapes; fall back to formatted JSON
  if (art.type === 'KeyFinding' && art.payload.summary) {
    return (
      <div style={{ marginTop: 10, padding: '10px 12px', background: 'rgba(245,158,11,0.07)', border: '1px solid rgba(245,158,11,0.2)', borderRadius: 8 }}>
        <p style={{ fontSize: 12.5, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
          {String(art.payload.summary)}
        </p>
      </div>
    );
  }

  return (
    <pre style={{
      marginTop: 8, padding: '8px 10px',
      background: 'var(--code-bg)', border: '1px solid var(--border)',
      borderRadius: 7, fontSize: 11, color: 'var(--code-text)',
      overflowX: 'auto', whiteSpace: 'pre-wrap', lineHeight: 1.55,
    }}>
      {JSON.stringify(art.payload, null, 2)}
    </pre>
  );
}

function ArtifactRow({ art, isExpanded, isActive, onToggle, panelRef }: {
  art: Artifact; isExpanded: boolean; isActive: boolean;
  onToggle: () => void; panelRef: React.RefObject<HTMLDivElement | null>;
}) {
  const cfg = ARTIFACT_CONFIG[art.type] ?? ARTIFACT_CONFIG.Chart;
  const rowRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isActive && rowRef.current && panelRef.current) {
      const panel = panelRef.current;
      const row = rowRef.current;
      panel.scrollTop = row.offsetTop - panel.offsetTop - 20;
    }
  }, [isActive]);

  const displayName = ARTIFACT_DISPLAY_NAME[art.type] ?? art.type;
  const timeLabel = art.created_at
    ? new Date(art.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    : '';

  return (
    <div
      ref={rowRef}
      style={{
        background: isActive ? 'rgba(212,149,74,0.06)' : 'var(--surface-2)',
        borderRadius: 9,
        border: isActive ? '1px solid rgba(212,149,74,0.35)' : '1px solid var(--border)',
        overflow: 'hidden',
        transition: 'border-color 0.2s, background 0.2s',
        boxShadow: isActive ? '0 0 0 2px rgba(212,149,74,0.1)' : 'none',
      }}
    >
      <div onClick={onToggle} style={{ display: 'flex', alignItems: 'center', gap: 9, padding: '8px 11px', cursor: 'pointer', userSelect: 'none' }}>
        <div style={{ width: 22, height: 22, borderRadius: 6, flexShrink: 0, background: cfg.bg, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <Icon name={cfg.icon} size={12} color={cfg.color} />
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 12.5, fontWeight: 500, color: 'var(--text-primary)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{art.name}</div>
          <div style={{ fontSize: 10.5, color: 'var(--text-muted)', marginTop: 1 }}>{displayName}</div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0 }}>
          {timeLabel && <span style={{ fontSize: 10.5, color: 'var(--text-muted)' }}>{timeLabel}</span>}
          <Icon name={isExpanded ? 'chevronUp' : 'chevronDown'} size={12} color="var(--text-muted)" />
        </div>
      </div>

      {isExpanded && (
        <div className="fade-in" style={{ padding: '0 11px 12px', borderTop: '1px solid var(--border)' }}>
          <ArtifactPayloadContent art={art} />
          {art.tags.length > 0 && (
            <div style={{ display: 'flex', gap: 5, marginTop: 8, flexWrap: 'wrap' }}>
              {art.tags.map((tag) => (
                <span key={tag} style={{ fontSize: 10.5, color: 'var(--text-muted)', background: 'var(--surface-3)', borderRadius: 99, padding: '2px 7px' }}>{tag}</span>
              ))}
            </div>
          )}
          <div style={{ display: 'flex', gap: 6, marginTop: 8, alignItems: 'center' }}>
            <button style={{
              marginLeft: 'auto', background: 'var(--surface-3)', border: '1px solid var(--border)',
              borderRadius: 6, padding: '3px 9px', cursor: 'pointer',
              fontSize: 11, color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: 4,
            }}>
              <Icon name="dashboard" size={10} /> Add to dash
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

export function ArtifactPanel() {
  const { artifacts, expandedArtifacts, toggleArtifact, setAllArtifacts, activeArtifact } = useSessionStore();
  const [filter, setFilter] = useState('All');
  const [search, setSearch] = useState('');
  const scrollRef = useRef<HTMLDivElement>(null);

  const filtered = artifacts.filter((a) =>
    (filter === 'All' || a.type === filter) &&
    (!search || a.name.toLowerCase().includes(search.toLowerCase())),
  );

  const allExpanded = filtered.length > 0 && filtered.every((a) => expandedArtifacts.has(a.id));

  return (
    <aside style={{
      width: 'var(--art-w)', flexShrink: 0,
      background: 'var(--surface-1)', borderLeft: '1px solid var(--border)',
      display: 'flex', flexDirection: 'column', height: '100%',
    }}>
      <div style={{ padding: '12px 12px 8px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 7 }}>
            <span style={{ fontSize: 12, fontWeight: 700, color: 'var(--text-secondary)', letterSpacing: '0.04em' }}>Artifacts</span>
            <span style={{ fontSize: 10.5, color: 'var(--text-muted)', background: 'var(--surface-3)', borderRadius: 99, padding: '1px 7px' }}>{artifacts.length}</span>
          </div>
          <button
            onClick={() => setAllArtifacts(filtered.map((a) => a.id), !allExpanded)}
            style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 11, color: 'var(--text-muted)', fontWeight: 500, padding: '2px 6px', borderRadius: 5 }}
          >
            {allExpanded ? 'Collapse all' : 'Expand all'}
          </button>
        </div>

        <input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search artifacts…"
          style={{
            width: '100%', background: 'var(--surface-2)', border: '1px solid var(--border)',
            borderRadius: 7, padding: '6px 10px', fontSize: 12, color: 'var(--text-primary)',
            outline: 'none', fontFamily: 'inherit', marginBottom: 8,
          }}
        />

        <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
          {FILTER_TYPES.map((t) => (
            <button key={t} onClick={() => setFilter(t)} style={{
              background: filter === t ? 'var(--accent-dim)' : 'var(--surface-3)',
              border: filter === t ? '1px solid rgba(212,149,74,0.4)' : '1px solid var(--border)',
              borderRadius: 99, padding: '3px 9px', cursor: 'pointer',
              fontSize: 10.5, fontWeight: filter === t ? 600 : 400,
              color: filter === t ? '#d4954a' : 'var(--text-muted)',
              transition: 'all 0.12s', whiteSpace: 'nowrap',
            }}>{ARTIFACT_DISPLAY_NAME[t] ?? t}</button>
          ))}
        </div>
      </div>

      <div ref={scrollRef} style={{ flex: 1, overflow: 'auto', padding: '8px 10px', display: 'flex', flexDirection: 'column', gap: 5 }}>
        {artifacts.length === 0 && (
          <div style={{ fontSize: 12, color: 'var(--text-muted)', textAlign: 'center', paddingTop: 24 }}>
            No artifacts yet — they appear here as the agent produces outputs.
          </div>
        )}
        {filtered.length === 0 && artifacts.length > 0 && (
          <div style={{ fontSize: 12, color: 'var(--text-muted)', textAlign: 'center', paddingTop: 24 }}>No artifacts match</div>
        )}
        {filtered.map((art) => (
          <ArtifactRow
            key={art.id}
            art={art}
            isExpanded={expandedArtifacts.has(art.id)}
            isActive={activeArtifact === art.id}
            onToggle={() => toggleArtifact(art.id)}
            panelRef={scrollRef}
          />
        ))}
      </div>

      <div style={{ padding: '10px 12px', borderTop: '1px solid var(--border)', flexShrink: 0 }}>
        <button style={{
          width: '100%', padding: '8px', borderRadius: 8,
          background: 'var(--accent-dim)', border: '1px solid rgba(212,149,74,0.3)',
          color: '#d4954a', fontWeight: 600, fontSize: 12.5, cursor: 'pointer',
          display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 7,
        }}>
          <Icon name="narrative" size={13} color="#d4954a" />
          Generate Narrative
        </button>
      </div>
    </aside>
  );
}
